# Generated by Django 2.0.2 on 2018-05-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhilianjob', '0004_auto_20180504_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='position',
            field=models.TextField(),
        ),
    ]
