# Generated by Django 2.0.2 on 2018-05-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhilianjob', '0005_auto_20180504_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
